### ISSUE TITLE
设置多个传送点后重启服务器后出错

### ISSUE THREAD

**Issue by RGHSSS** [Enron233/RandomTp#1]
当设置多个传送点后，重启服务器后传送点会全部丢失，后台报错。

`[04:44:32 INFO]: [ScriptBlock] RGHSSS 触发了 walk 脚本方块...
[04:44:32 INFO]: [ScriptBlock] 在坐标 test,-820,8,172
[04:44:32 ERROR]: Could not pass event PlayerMoveEvent to ScriptBlock v0.8.72CN
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
>Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'anrtp' in plugin RandomTp v1.0.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:273) ~[CraftPlayer.class:1.7.10-R0.1-SNAPSHOT]
at scriptblock.options.permissions.BypassOp.isValid(BypassOp.java:25) ~[?:?]
at scriptblock.options.SBOption.onOptionCall(SBOption.java:72) ~[?:?]
at scriptblock.options.OptionHandler.readScript(OptionHandler.java:115) ~[?:?]
at scriptblock.listeners.PlayerWalkBlock.onPlayerMove(PlayerWalkBlock.java:90) ~[?:?]
at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
... 13 more
>Caused by: java.lang.NullPointerException
at iam.xiaoan.randomtp.Command.Acommand.onCommand(Acommand.java:60) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:273) ~[CraftPlayer.class:1.7.10-R0.1-SNAPSHOT]
at scriptblock.options.permissions.BypassOp.isValid(BypassOp.java:25) ~[?:?]
at scriptblock.options.SBOption.onOptionCall(SBOption.java:72) ~[?:?]
at scriptblock.options.OptionHandler.readScript(OptionHandler.java:115) ~[?:?]
at scriptblock.listeners.PlayerWalkBlock.onPlayerMove(PlayerWalkBlock.java:90) ~[?:?]
at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]`

`[04:47:35 INFO]: TitanGy issued server command: /anrtp set place list
[04:47:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'anrtp' in plugin RandomTp v1.0.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
>Caused by: java.lang.NullPointerException
at iam.xiaoan.randomtp.Command.Acommand.onCommand(Acommand.java:90) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
... 13 more`

**Comment by RGHSSS** [comment]
翻阅后台后发现是这一行出错：
Set<String> listFirst = getIns().getConfig().getConfigurationSection("place").getKeys(true);
